version: '3.8'

services:
  gramps:
    image: ghcr.io/gramps-project/grampsweb:latest
    container_name: gramps
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data/gramps:/root/.gramps
      - ./data/users:/app/users
      - ./data/indexdir:/app/indexdir
      - ./data/media:/app/media
      - ./data/secret:/app/secret
      - ./data/persist:/app/persist
    environment:
      - GRAMPSWEB_USERNAME=${GRAMPSWEB_USERNAME}
      - GRAMPSWEB_PASSWORD=${GRAMPSWEB_PASSWORD}
      - GRAMPSWEB_TREE=${GRAMPSWEB_TREE}
      - GRAMPSWEB_REGISTRATION_DISABLED=${GRAMPSWEB_REGISTRATION_DISABLED}

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - TZ=Europe/Moscow
  #   command: --schedule "0 5 * * *"

volumes:
  caddy_data:
  caddy_config:


